
DROP PROCEDURE IF EXISTS OBTENER_CLIENTE;

CREATE PROCEDURE  OBTENER_CLIENTE ( 
	@ID_CLIENTE INT 
)
AS BEGIN

SELECT * FROM Cliente WHERE CLIENTE_ID = @ID_CLIENTE

END

DROP PROCEDURE IF EXISTS OBTENER_SALDO;

CREATE PROCEDURE  OBTENER_SALDO ( 
	@CUENTA VARCHAR(100) 
)
AS BEGIN

SELECT * FROM Estado_Cuenta 
WHERE NUMERO_CUENTA = @CUENTA

END

DROP PROCEDURE IF EXISTS ACTUALIZAR_FONDOS;

CREATE PROCEDURE ACTUALIZAR_FONDOS(
	@CUENTA VARCHAR(100),
	@SALDO_ACTUALIZADO VARCHAR(100)
)
AS BEGIN

UPDATE Estado_Cuenta

SET SALDO = @SALDO_ACTUALIZADO

WHERE NUMERO_CUENTA = @CUENTA

END

DROP PROCEDURE IF EXISTS AGREGAR_MOVIMIENTO;

CREATE PROCEDURE AGREGAR_MOVIMIENTO(
	@NUMERO_CUENTA VARCHAR(100) = NULL,
	@TIPO VARCHAR(50) = NULL,
	@MONTO VARCHAR(100) = NULL,
	@IBAN VARCHAR(50) = NULL
) 
AS BEGIN

INSERT INTO Movimientos (NUMERO_CUENTA, TIPO, MONTO, IBAN)
	VALUES( @NUMERO_CUENTA, @TIPO, @MONTO, @IBAN )
END


DROP PROCEDURE IF EXISTS OBTENER_CUENTA;

CREATE PROCEDURE OBTENER_CUENTA(
	@CUENTA VARCHAR(100)
) 
AS BEGIN

SELECT * FROM Producto 
WHERE NUMERO_CUENTA = @CUENTA

END
