USE BancaEnLinea

DROP TABLE IF EXISTS "Producto";
DROP TABLE IF EXISTS "Cliente";
DROP TABLE IF EXISTS "Movimientos";
DROP TABLE IF EXISTS "Estado_Cuenta";
DROP TABLE IF EXISTS "Producto_Historico";

CREATE TABLE Cliente
(
	CLIENTE_ID INT NOT NULL IDENTITY(1,1),
	IDENTIFICACION VARCHAR(100) UNIQUE,
	NOMBRE VARCHAR(100),
	PRIMARY KEY(CLIENTE_ID)
)

CREATE TABLE Producto
(
	PRODUCTO_ID INT NOT NULL IDENTITY(1,1) ,
	NUMERO_CUENTA VARCHAR(100) UNIQUE,
	CLIENTE_ID INT REFERENCES Cliente(CLIENTE_ID),
	TIPO_PRODUCTO VARCHAR(50),
	MONEDA VARCHAR(50),
	FECHA_APERTURA VARCHAR(50),
	IBAN VARCHAR(50),
	ESTADO VARCHAR(2),
	TASA_INTERES FLOAT
	PRIMARY KEY(PRODUCTO_ID)
)

CREATE TABLE Movimientos
(
	ID INT NOT NULL IDENTITY(1,1),
	NUMERO_CUENTA VARCHAR(100) REFERENCES Producto(NUMERO_CUENTA),
	TIPO VARCHAR(50),
	MONTO VARCHAR(100),
	IBAN VARCHAR(50),
	PRIMARY KEY(NUMERO_CUENTA)
)

CREATE TABLE Estado_Cuenta
(
	NUMERO_CUENTA VARCHAR(100) REFERENCES Producto(NUMERO_CUENTA),
	MONEDA VARCHAR(50),
	SALDO VARCHAR(100),
	ULTIMA_ACTUALIZACION VARCHAR(50)
	PRIMARY KEY(NUMERO_CUENTA)
)





CREATE TABLE Producto_Historico
(
	ID INT NOT NULL IDENTITY(1,1),
	PRODUCTO_ID INT NOT NULL ,
	NUMERO_CUENTA VARCHAR(100),
	CLIENTE_ID INT ,
	TIPO_PRODUCTO VARCHAR(50),
	MONEDA VARCHAR(50),
	FECHA_APERTURA VARCHAR(50),
	IBAN VARCHAR(50),
	ESTADO VARCHAR(2),
	TASA_INTERES FLOAT
	PRIMARY KEY(PRODUCTO_ID)
)



